### ISSUE TITLE
protobuf package

### ISSUE THREAD

**Issue by air55555** [pvjosue/LFMNet#3]
Error while  training. Logs attached 
C:\Users\LRS\PycharmProjects\LFMNet\venv\Scripts\python.exe C:/Users/LRS/PycharmProjects/LFMNet/mainTrain.py --epochs 1000 --valEvery 0.25 --imagesToUse 0 1 2 3 4 5 --GPUs 0 --batchSize 64 --validationSplit 0.1 --biasVal 0.1 --learningRate 0.005 --useBias True --useSkipCon False --fovInput 9 --neighShape 3 --useShallowUnet True --ths 0.03 --datasetPath BrainLFMConfocalDataset/Brain_40x_64Depths_362imgs.h5 --outputPath, nargs='? runs/ --outputPrefix "" --checkpointPath ""
Traceback (most recent call last):
  File "C:/Users/LRS/PycharmProjects/LFMNet/mainTrain.py", line 4, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\LRS\PycharmProjects\LFMNet\venv\lib\site-packages\torch\utils\tensorboard\__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
  File "C:\Users\LRS\PycharmProjects\LFMNet\venv\lib\site-packages\tensorboard\summary\__init__.py", line 25, in <module>
    from tensorboard.summary import v1
  File "C:\Users\LRS\PycharmProjects\LFMNet\venv\lib\site-packages\tensorboard\summary\v1.py", line 24, in <module>
    from tensorboard.plugins.audio import summary as _audio_summary
  File "C:\Users\LRS\PycharmProjects\LFMNet\venv\lib\site-packages\tensorboard\plugins\audio\summary.py", line 36, in <module>
    from tensorboard.plugins.audio import metadata
  File "C:\Users\LRS\PycharmProjects\LFMNet\venv\lib\site-packages\tensorboard\plugins\audio\metadata.py", line 21, in <module>
    from tensorboard.compat.proto import summary_pb2
  File "C:\Users\LRS\PycharmProjects\LFMNet\venv\lib\site-packages\tensorboard\compat\proto\summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "C:\Users\LRS\PycharmProjects\LFMNet\venv\lib\site-packages\tensorboard\compat\proto\tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "C:\Users\LRS\PycharmProjects\LFMNet\venv\lib\site-packages\tensorboard\compat\proto\resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "C:\Users\LRS\PycharmProjects\LFMNet\venv\lib\site-packages\tensorboard\compat\proto\tensor_shape_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "C:\Users\LRS\PycharmProjects\LFMNet\venv\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Process finished with exit code 1

**Comment by air55555** [comment]
pip3 install --upgrade protobuf==3.20.0 fixed the issue
